name = "sheltersync"
main = "src/index.ts"
compatibility_date = "2023-05-15"

kv_namespaces = [
      { binding = "SYNC_KV", id = "5b2754a1d77840a09a74ff310b1c5893" },
      { binding = "POLL_KV", id = "151ff3f1f120418d866964c72acf0fea" }
]

[vars]
REDIR_URL = "https://sheltersync.uwunet.workers.dev/api/oauth"

[env.development]
kv_namespaces = [
    { binding = "SYNC_KV", id = "00117f9e4c71479088ce9bc3fc6a38c4", preview_id = "00117f9e4c71479088ce9bc3fc6a38c4" },
    { binding = "POLL_KV", id = "a95daab7a44d4236afaa913d9a61ec67", preview_id = "a95daab7a44d4236afaa913d9a61ec67" }
]

[env.development.vars]
REDIR_URL = "http://localhost:8787/api/oauth"